# services/interpretation-service/app/prompt_assembler.py

import json
import asyncio
from typing import List, Dict, Any, Optional, Literal

# Import schemas for type hinting and data structuring
from .schemas import SynthesisRuleMetadata, Valence

# Import custom exceptions from the main application file
from .exceptions import UpstreamServiceError, ComponentNotFoundError

# =============================================================================
# I. PROMPT TEMPLATE PLACEHOLDERS & FRAMEWORK RULES
# =============================================================================
# As requested, these are placeholders. The full prompt strings from
# 'validate_prompts.py' will be pasted here during implementation.

# --- Stage 1: Valence Prompts ---
VALENCE_PROMPT_PLANET_IN_SIGN = """

            You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a planet residing within a zodiac sign by applying the specific astrological rule known as **The Zodiacal Lens**.

                

            **Interpretive Rule to Apply: The Zodiacal Lens**

            * The sign a planet occupies acts as a "lens, costume, or environment," dictating the **style and quality** of how that planetary drive is expressed.

            * **Governing System:** This interplay is evaluated through the **System of Essential Dignities**, which provides the rules for a planet's strength and efficacy in a sign:

                        * **Domicile (Rulership):** The planet is in its own kingdom, expressing its nature purely and powerfully.

                        * **Exaltation:** The planet is an honored guest, with its energy amplified and focused effectively.

                        * **Detriment:** The planet is in "exile," in an environment contrary to its nature, requiring challenging negotiation.

                        * **Fall:** The planet's core principle is fundamentally challenged, weakening or distorting its expression.



            **Your Task:**
            1.      Analyze the provided Planet, Sign, and Essential Dignity status to determine the core synthesized energy.
            2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
            3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).
                            

            **CRITICAL INSTRUCTIONS:**

            * DO NOT explain the rule or your process.

            * Your response MUST be only the raw JSON object.

                

            **Components for Synthesis:**

                

            **[PLANET_DATA]**

                

            **[SIGN_DATA]**

                

            **Essential Dignity Status:** [DIGNITY_STATUS]
"""
VALENCE_PROMPT_PLANET_IN_HOUSE = """ You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a planet residing within a house by applying the specific astrological rules of **The Stage Metaphor** and **The Rhythmic Unfolding (House Qualities)**.

                

            **Interpretive Rules to Apply:**

                

            1.      **The Stage Metaphor:**

                        * The planet is the "archetypal actor," and the house is the "stage" or **specific domain of life** where that actor's energy and drama unfolds. The interpretation is generated by placing the planet's core drive within the context of the house's life affairs.

                

            2.      **The Rhythmic Unfolding (House Quality):**

                        * This quality describes the **dynamic mode of expression** for the planet on that stage.

                        * **Angular (Action):** A point of direct, forceful manifestation and initiation.

                        * **Succedent (Consolidation):** Secures and gives substance to initiatives.

                        * **Cadent (Integration):** Processes, analyzes, and distributes experiences.

                

            **Your Task:**
            1.  Analyze the provided astrological components and the core principle of the interpretive rule.
            2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
            3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).


                

            **CRITICAL INSTRUCTIONS:**

            * DO NOT explain the rules or your process.

            * Your response MUST be only the raw JSON object.

                

            **Components for Synthesis:**

                

            **[PLANET_DATA]**

                

            **[HOUSE_DATA]**

                

            **House Quality:** [QUALITY_DATA]
"""

VALENCE_PROMPT_PLANET_ASPECT_PLANET =  """
            You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for two planets in aspect by applying the specific astrological rule known as **The Archetypal Dialogue**.

                            

            **Interpretive Rule to Apply: The Archetypal Dialogue**

            * **Core Principle:** Aspects represent the geometric and psychological **dialogue between two planetary drives**, describing how different functions within the psyche support or challenge one another.

            * **Governing System:** The nature of the dialogue is defined by the **Principle of Interplay** associated with the specific aspect:

            * **The Fusion Principle (Conjunction):** The archetypes merge and act as a single, unified force.

            * **The Harmony Principle (Trine & Sextile):** The archetypes support each other naturally, representing innate talents and ease.

            * **The Conflict & Growth Principle (Square & Opposition):** The archetypes are in a state of tension that demands conscious awareness and forces developmental growth.

            * **The Adjustment Principle (Inconjunct):** The archetypes share nothing in common, creating a blind spot that requires constant, conscious adjustment.

                            
            **Your Task:**
            1.  Analyze the provided astrological components and the core principle of the interpretive rule. Apply **The Archetypal Dialogue** rule, using the specific **Principle of Interplay** provided by the aspect, to understand the nature of the interaction between the two planetary drives.
            2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
            3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).

                                        

            **CRITICAL INSTRUCTIONS:**

            * Your response MUST be only the raw JSON object.

            * DO NOT explain the rule or your process.

                            

            **Components for Synthesis:**

                            

            **[PLANET_1_DATA]**

                            

            **[PLANET_2_DATA]**

                            

            **[ASPECT_DATA]** (This will include the name of the principle and its definition)
"""
VALENCE_PROMPT_SIGN_ON_HOUSE = """     

            You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a zodiac sign on a house cusp by applying the specific astrological rule known as **The Adverbial Signature**.



            **Interpretive Rule to Apply: The Adverbial Signature**

            * **Core Principle:** The sign on a house cusp acts as an "adjective" or adverbial signature, describing the **tone, style, and conditions** one encounters in that area of life.

            * **Governing System:** The interpretation is generated by modifying the house's topics with the qualities of the sign on its cusp. For example, Capricorn on the 2nd House cusp suggests a disciplined and pragmatic approach to finances.  


            **Your Task:**
            1.  Analyze the provided astrological components and the core principle of the interpretive rule. Apply **The Adverbial Signature** rule to understand how the Sign's qualities modify the topics of the House. Identify the House's domain (e.g., "Financial Security" for the 2nd House) as the **primary context**.
            2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
            3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).

            **CRITICAL INSTRUCTIONS:**

            * DO NOT explain the rule or your process.

            * Your response MUST be only the raw JSON object.



            **Components for Synthesis:**



            **[SIGN_DATA]**



            **[HOUSE_DATA]**
"""
VALENCE_PROMPT_NODE_IN_SIGN = """
You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a lunar node residing within a zodiac sign by applying the specific astrological rule known as **The Zodiacal Lens (Extended for Nodes)**.



**Interpretive Rule to Apply: The Zodiacal Lens (Extended for Nodes)**

* Core Principle: The sign a component occupies acts as a "lens, costume, or environment," dictating the **style and quality** of how that component's core principle is expressed. For a **Node**, this is its **evolutionary purpose (North Node) or karmic pattern (South Node)**.

* Governing System: The interpretation is generated by modifying the Node's core theme with the archetypal qualities of the sign it occupies. While planets are evaluated through Essential Dignities, Nodes are evaluated by how the sign's characteristics provide the essential pathway for the Node's function.



**Your Task:**
1.  Analyze the provided astrological components and the core principle of the interpretive rule.
2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).




**CRITICAL INSTRUCTIONS:**

* DO NOT explain the rule or your process.

* Your response MUST be only the raw JSON object.



**Components for Synthesis:**



**[NODE_DATA]**



**[SIGN_DATA]**

"""     
VALENCE_PROMPT_NODE_IN_HOUSE = """
You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a lunar node residing within a house by applying the specific astrological rules of **The Stage Metaphor (Extended for Nodes)** and **The Rhythmic Unfolding (House Qualities)**.



**Interpretive Rules to Apply:**



1.      **The Stage Metaphor (Extended for Nodes):**

            * [cite_start]The house is the "stage" or **specific domain of life** where an archetypal principle's story unfolds[cite: 3272, 3273]. For a **Node**, it is the **karmic or evolutionary theme** that is played out in that specific life area.



2.      **The Rhythmic Unfolding (House Quality):**

            * This quality describes the **dynamic mode of expression** for the Node's theme on that stage.

            * [cite_start]**Angular (Action):** A point of direct, forceful manifestation and initiation[cite: 2448, 2449].

            * [cite_start]**Succedent (Consolidation):** Secures and gives substance to the theme[cite: 2450, 2451].

            * [cite_start]**Cadent (Integration):** Processes, analyzes, and distributes the theme's experiences[cite: 2452, 2453].



**Your Task:**
1.  Analyze the provided astrological components and the core principle of the interpretive rule.
2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).




**CRITICAL INSTRUCTIONS:**

* DO NOT explain the rules or your process.

* Your response MUST be only the raw JSON object.



**Components for Synthesis:**



**[NODE_DATA]**



**[HOUSE_DATA]**



**House Quality:** [QUALITY_DATA] """
VALENCE_PROMPT_PLANET_ASPECT_ANGLE = """

You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a planet aspecting a chart angle by applying the specific astrological rule known as **The Archetypal Imprint**.



**Interpretive Rule to Apply: The Archetypal Imprint**

* **Core Principle:** This framework defines how a planet's core drive **imprints upon, activates, or challenges** one of the four fundamental pillars of the life structure. This is not a dialogue between two equal drives, but the infusion of a dynamic planetary energy into a core area of lived experience (e.g., Identity, Home, Partnership, or Career).

* **Governing System:** The nature of the imprint is defined by the **Principle of Interplay** associated with the specific aspect. The Angle acts as the sensitive focal point that receives and expresses the planet's energy according to the aspect's nature.

            * [cite_start]**The Fusion Principle (Conjunction):** The planetary drive and the Angle's life domain are completely merged[cite: 89].

            * [cite_start]**The Harmony Principle (Trine & Sextile):** The planet's energy naturally and easily supports the affairs of the Angle[cite: 90].

            * [cite_start]**The Conflict & Growth Principle (Square & Opposition):** The planet's drive creates dynamic tension with the Angle's domain, forcing action and developmental growth[cite: 91].

            * [cite_start]**The Adjustment Principle (Inconjunct):** The planet's energy has a blind-spot relationship to the Angle's domain, requiring constant, conscious adjustments[cite: 92].



**Your Task:**
1.  Analyze the provided astrological components and the core principle of the interpretive rule.
2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).




**CRITICAL INSTRUCTIONS:**

* DO NOT explain the rule or your process.

* Your response MUST be only the raw JSON object.



**Components for Synthesis:**



**[PLANET_DATA]**



**[ANGLE_DATA]**



**[ASPECT_DATA]** (This will include the name of the principle and its definition)

"""
VALENCE_PROMPT_PLANET_ASPECT_NODE = """     

You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a planet aspecting a lunar node by applying the specific astrological rule known as **The Karmic Infusion**.



**Interpretive Rule to Apply: The Karmic Infusion**

* **Core Principle:** This framework describes how a planetary drive **infuses its energy into the user's evolutionary path**. The planet acts as a tool, a gift, a challenge, or a distraction that directly influences the karmic and developmental journey from the South Node (past habits, innate talents) to the North Node (future growth, soul purpose).

* **Governing System:** The nature of the infusion is defined by the **Principle of Interplay** associated with the specific aspect. The aspect reveals how the planet's archetype functions in relation to the nodal story.

            * **The Fusion Principle (Conjunction):** The planet's energy is fundamentally intertwined with the Node's theme, representing a core energy to be worked with.

            * **The Harmony Principle (Trine & Sextile):** The planet represents an innate gift or talent that can be easily used to support the evolutionary journey.

            * **The Conflict & Growth Principle (Square & Opposition):** The planet's energy represents a primary "karmic lesson" or developmental challenge that must be integrated to move forward.

            * **The Adjustment Principle (Inconjunct):** The planet's energy feels disconnected from the soul's path, requiring ongoing, conscious effort to be integrated.



**Your Task:**
1.  Analyze the provided astrological components and the core principle of the interpretive rule.
2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).



**CRITICAL INSTRUCTIONS:**

* DO NOT explain the rule or your process.

* Your response MUST be only the raw JSON object.



**Components for Synthesis:**



**[PLANET_DATA]**



**[NODE_DATA]**



**[ASPECT_DATA]** (This will include the name of the principle and its definition)



"""
VALENCE_PROMPT_NODE_ASPECT_ANGLE = """ You are an expert archetypal astrologer. Your task is to identify the core archetypal expressions, or "valences," for a lunar node aspecting a chart angle by applying the specific astrological rule known as **The Soul's Compass**.



**Interpretive Rule to Apply: The Soul's Compass**

* **Core Principle:** This framework defines how the soul's evolutionary path (the Nodal Axis) is **grounded in, expressed through, or challenged by** the most tangible pillars of the life structure (the Angles).

* **Governing System:** The nature of this alignment is defined by the **Principle of Interplay** associated with the specific aspect. The interpretation is generated by synthesizing the theme of the Node with the life domain of the Angle, as filtered through the aspect's dynamic.

            * **The Fusion Principle (Conjunction):** The Node's theme and the Angle's domain are inextricably linked, making the life area a primary vehicle for the soul's journey.

            * **The Harmony Principle (Trine & Sextile):** The Angle's life domain provides a natural and supportive stage for the karmic work of the Nodes.

            * **The Conflict & Growth Principle (Square & Opposition):** The Angle's life domain is in dynamic tension with the nodal path, creating a central life challenge that forces growth.

            * **The Adjustment Principle (Inconjunct):** The Angle's life domain and the soul's path feel disconnected, requiring conscious effort to align them.



**Your Task:**
1.  Analyze the provided astrological components and the core principle of the interpretive rule.
2.  Generate a list of 3-5 distinct "expression archetypes" (valences) that represent the different potential manifestations of this energy, from the most constructive to the most challenging.
3.  Format the final output as a JSON object with a single key "valences". This key should contain a list of objects, where each object has two keys: "archetype" (the name of the valence, e.g., "The Spiritual Warrior") and "description" (a brief, one-sentence explanation of what this expression represents).


**CRITICAL INSTRUCTIONS:**


* DO NOT explain the rule or your process.

* Your response MUST be only the raw JSON object.



**Components for Synthesis:**



**[NODE_DATA]**



**[ANGLE_DATA]**



**[ASPECT_DATA]** (This will include the name of the principle and its definition)



"""

# --- Stage 2: Manifestation Prompts ---
PSYCHOLOGICAL_PATTERNS_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe the potential psychological patterns for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter, lens, or pathway. It specifies how the broader, more abstract energy of an astrological signature manifests as a concrete psychological reality.
* **Governing System:** The interpretation is generated by describing the core psychological functions—the potential strengths and the potential shadows—that are most aligned with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's psychological expression.
3.  Generate 2-3 detailed psychological patterns. For each pattern, describe its core dynamic and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "psychological_patterns". This key should contain a list of objects, where each object has three keys: "pattern_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
RELATIONAL_DYNAMICS_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe the potential relational dynamics for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests in one-on-one connections with others.
* **Governing System:** The interpretation is generated by describing how the chosen valence is likely to play out in partnerships, friendships, and family life, highlighting both the potential strengths and shadows of that expression.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's expression in relationships.
3.  Generate 2-3 detailed relational dynamics. For each dynamic, describe its core pattern and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "relational_dynamics". This key should contain a list of objects, where each object has three keys: "dynamic_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
OCCUPATIONAL_ARENAS_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe the potential occupational arenas for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests in the domain of work and career.
* **Governing System:** The interpretation is generated by describing the broad fields of work, career environments, and professional styles that are most aligned with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's expression in a professional context.
3.  Generate 2-3 detailed occupational arenas. For each, describe the environment or style and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "occupational_arenas". This key should contain a list of objects, where each object has three keys: "arena_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
CREATIVE_EXPRESSION_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe the potential avenues for creative expression for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests through artistic, theatrical, or other creative outlets.
* **Governing System:** The interpretation is generated by describing the types of creative pursuits and self-expressive styles that are most aligned with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's creative expression.
3.  Generate 2-3 detailed avenues of creative expression. For each, describe the creative style and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "creative_expression". This key should contain a list of objects, where each object has three keys: "expression_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
HEALTH_AND_WELLNESS_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe the potential health and wellness manifestations for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests in the physical body and well-being routines.
* **Governing System:** The interpretation is generated by describing potential connections to the physical body, typical stress responses, and preferred activities for maintaining well-being that are most aligned with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's expression in health and wellness.
3.  Generate 2-3 detailed health and wellness manifestations. For each, describe the pattern and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "health_and_wellness". This key should contain a list of objects, where each object has three keys: "manifestation_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
FINANCIAL_STYLE_PROMPT =  """ 
You are an expert archetypal astrologer. Your task is to describe the potential financial style for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests in one's approach to resources.
* **Governing System:** The interpretation is generated by describing the archetypal approach to earning, spending, saving, and investing that is most aligned with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's financial style.
3.  Generate 2-3 detailed financial styles. For each, describe the approach and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "financial_style". This key should contain a list of objects, where each object has three keys: "style_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""
LEISURE_AND_HOBBIES_PROMPT = """ 
You are an expert archetypal astrologer. Your task is to describe potential leisure activities and hobbies for an astrological signature as expressed through a specific, pre-defined valence.

**Interpretive Rule to Apply: The Archetypal Specification**
* **Core Principle:** A "valence" is a specific archetypal expression that acts as a filter or lens. It specifies how the broader energy of an astrological signature manifests in personal interests and fulfilling experiences.
* **Governing System:** The interpretation is generated by describing the types of personal interests, hobbies, and activities that resonate most with the chosen valence.

**Your Task:**
1.  Analyze the provided Astrological Signature and the chosen Valence Archetype.
2.  Reflect on how this specific valence would shape the signature's expression in leisure time.
3.  Generate 2-3 detailed leisure activities or hobbies. For each, describe the activity and classify it as either a "strength" or a "shadow."
4.  Format the final output as a JSON object with a single key "leisure_and_hobbies". This key should contain a list of objects, where each object has three keys: "activity_name" (a short, evocative title), "description" (a 1-2 sentence explanation), and "type" ("strength" or "shadow").

**CRITICAL INSTRUCTIONS:**
* DO NOT explain the rule or your process.
* Your response MUST be only the raw JSON object.

**Components for Synthesis:**

**Astrological Signature:**
[SIGNATURE_DATA]

**Chosen Valence:**
[VALENCE_DATA]
"""

# --- Dispatcher Dictionaries ---
# These dictionaries map a determined 'test_type' or 'life_area' to the correct prompt template.
VALENCE_PROMPTS = {
    'planet_in_sign': VALENCE_PROMPT_PLANET_IN_SIGN,
    'planet_in_house': VALENCE_PROMPT_PLANET_IN_HOUSE,
    'planet_aspect_planet': VALENCE_PROMPT_PLANET_ASPECT_PLANET,
    'sign_on_house': VALENCE_PROMPT_SIGN_ON_HOUSE,
    'node_in_sign': VALENCE_PROMPT_NODE_IN_SIGN,
    'node_in_house': VALENCE_PROMPT_NODE_IN_HOUSE,
    'planet_aspect_angle': VALENCE_PROMPT_PLANET_ASPECT_ANGLE,
    'planet_aspect_node': VALENCE_PROMPT_PLANET_ASPECT_NODE,
    'node_aspect_angle': VALENCE_PROMPT_NODE_ASPECT_ANGLE
}

MANIFESTATION_PROMPTS = {
    'psychological_patterns': PSYCHOLOGICAL_PATTERNS_PROMPT,
    'relational_dynamics': RELATIONAL_DYNAMICS_PROMPT,
    'occupational_arenas': OCCUPATIONAL_ARENAS_PROMPT,
    'creative_expression': CREATIVE_EXPRESSION_PROMPT,
    'health_and_wellness': HEALTH_AND_WELLNESS_PROMPT,
    'financial_style': FINANCIAL_STYLE_PROMPT,
    'leisure_and_hobbies': LEISURE_AND_HOBBIES_PROMPT,
}

# --- Framework Rules & Dignity Logic ---
# In a real system, this would be loaded from a configuration file or knowledge base.
# For now, it's defined here to make the logic explicit.
FRAMEWORK_RULES = {
    "The Zodiacal Lens": {"name": "The Zodiacal Lens", "description": "The sign a planet occupies acts as a 'lens, costume, or environment,'..."},
    "The Stage Metaphor": {"name": "The Stage Metaphor", "description": "The planet is the 'archetypal actor,' and the house is the 'stage'..."},
    "The Archetypal Dialogue": {"name": "The Archetypal Dialogue", "description": "Aspects represent the geometric and psychological dialogue between two planetary drives..."},
    "The Adverbial Signature": {"name": "The Adverbial Signature", "description": "The sign on a house cusp acts as an 'adjective' or adverbial signature..."},
    "The Zodiacal Lens (Extended for Nodes)": {"name": "The Zodiacal Lens (Extended for Nodes)", "description": "The sign a component occupies acts as a 'lens, costume, or environment,'..."},
    "The Stage Metaphor (Extended for Nodes)": {"name": "The Stage Metaphor (Extended for Nodes)", "description": "The house is the 'stage' or specific domain of life where an archetypal principle's story unfolds..."},
    "The Archetypal Imprint": {"name": "The Archetypal Imprint", "description": "This framework defines how a planet's core drive imprints upon, activates, or challenges one of the four fundamental pillars of the life structure."},
    "The Karmic Infusion": {"name": "The Karmic Infusion", "description": "This framework describes how a planetary drive infuses its energy into the user's evolutionary path."},
    "The Soul's Compass": {"name": "The Soul's Compass", "description": "This framework defines how the soul's evolutionary path (the Nodal Axis) is grounded in, expressed through, or challenged by the most tangible pillars of the life structure (the Angles)."},
}

ESSENTIAL_DIGNITIES = {
    "sun": {"domicile": "leo", "exaltation": "aries", "detriment": "aquarius", "fall": "libra"},
    "moon": {"domicile": "cancer", "exaltation": "taurus", "detriment": "capricorn", "fall": "scorpio"},
    "mercury": {"domicile": ["gemini", "virgo"], "exaltation": "virgo", "detriment": ["sagittarius", "pisces"], "fall": "pisces"},
    "venus": {"domicile": ["taurus", "libra"], "exaltation": "pisces", "detriment": ["scorpio", "aries"], "fall": "virgo"},
    "mars": {"domicile": ["aries", "scorpio"], "exaltation": "capricorn", "detriment": ["libra", "taurus"], "fall": "cancer"},
    "jupiter": {"domicile": ["sagittarius", "pisces"], "exaltation": "cancer", "detriment": ["gemini", "virgo"], "fall": "capricorn"},
    "saturn": {"domicile": ["capricorn", "aquarius"], "exaltation": "libra", "detriment": ["cancer", "leo"], "fall": "aries"},
}


class PromptAssembler:
    """
    Assembles LLM prompts for the two-stage valence and manifestation flow.
    This module encapsulates the 'white box' prompting philosophy by dynamically
    selecting rule-based prompt templates and populating them with canonical data.
    """

    def __init__(self, lexicon_client: Any, calculation_client: Any):
        self.lexicon_client = lexicon_client
        self.calculation_client = calculation_client

    def _determine_synthesis_type_and_rule(self, components: List[Dict[str, str]]) -> (str, str):
        """
        Parses the component list to determine the astrological pattern (synthesis type)
        and the corresponding generative framework rule name.
        """
        num_components = len(components)
        types = [c['type'] for c in components]

        if num_components == 2:
            if types == ['planet', 'zodiac_sign']: return 'planet_in_sign', "The Zodiacal Lens"
            if types == ['planet', 'house']: return 'planet_in_house', "The Stage Metaphor"
            if types == ['node', 'zodiac_sign']: return 'node_in_sign', "The Zodiacal Lens (Extended for Nodes)"
            if types == ['node', 'house']: return 'node_in_house', "The Stage Metaphor (Extended for Nodes)"
            if types == ['zodiac_sign', 'house']: return 'sign_on_house', "The Adverbial Signature"
        
        elif num_components == 3:
            if types == ['planet', 'dynamic', 'planet']: return 'planet_aspect_planet', "The Archetypal Dialogue"
            if types == ['planet', 'dynamic', 'angle']: return 'planet_aspect_angle', "The Archetypal Imprint"
            if types == ['planet', 'dynamic', 'node']: return 'planet_aspect_node', "The Karmic Infusion"
            if types == ['node', 'dynamic', 'angle']: return 'node_aspect_angle', "The Soul's Compass"

        raise ValueError(f"Unsupported component combination for synthesis: {types}")

    def _get_dignity_status(self, planet_id: str, sign_id: str) -> str:
        """Determines the essential dignity of a planet in a sign."""
        dignities = ESSENTIAL_DIGNITIES.get(planet_id, {})
        for dignity, sign in dignities.items():
            if isinstance(sign, list) and sign_id in sign:
                return dignity.capitalize()
            if sign_id == sign:
                return dignity.capitalize()
        return "Peregrine" # Default status if no specific dignity

    async def _get_required_data(self, components: List[Dict[str, str]], birth_data: Optional[Dict[str, Any]]) -> (List[Dict[str, Any]], Optional[Dict[str, Any]]):
        """Orchestrates fetching all necessary data from upstream services."""
        tasks = [self.lexicon_client.get_component_detail(comp['type'], comp['id']) for comp in components]
        components_data = await asyncio.gather(*tasks)

        calculated_chart = None
        if birth_data:
            calculated_chart = await self.calculation_client.get_natal_chart(birth_data)
            
        return components_data, calculated_chart

    def _build_prompt_string(self, template: str, replacements: Dict[str, str]) -> str:
        """Replaces placeholders in a template string with provided values."""
        prompt = template
        for placeholder, value in replacements.items():
            if placeholder in prompt:
                prompt = prompt.replace(placeholder, str(value))
        return prompt

    async def assemble_valence_prompt(self, components_input: List[Dict[str, str]], birth_data: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Assembles the prompt for Stage 1: Generating Valences."""
        synthesis_type, rule_name = self._determine_synthesis_type_and_rule(components_input)
        
        components_data, calculated_chart = await self._get_required_data(components_input, birth_data)

        template = VALENCE_PROMPTS.get(synthesis_type)
        if not template:
            raise ValueError(f"No valence prompt template found for synthesis type: {synthesis_type}")
            
        rule_metadata = FRAMEWORK_RULES.get(rule_name)
        if not rule_metadata:
            raise ValueError(f"Framework rule '{rule_name}' not found.")

        # Prepare placeholder replacements
        replacements = {}
        planet_count = 1
        dignity_status = "N/A"
        quality_data = "N/A"
        
        # Temporary storage for dignity calculation
        planet_for_dignity, sign_for_dignity = None, None

        for i, comp_data in enumerate(components_data):
            comp_type = components_input[i]['type']
            comp_id = components_input[i]['id']

            if comp_type == 'planet':
                # Handles prompts with [PLANET_1_DATA] and [PLANET_2_DATA]
                key = f"[PLANET_{planet_count}_DATA]"
                replacements[key] = json.dumps(comp_data)
                if planet_count == 1: # Only assign the first planet for dignity calc
                    planet_for_dignity = comp_id
                planet_count += 1
            elif comp_type == 'zodiac_sign':
                replacements['[SIGN_DATA]'] = json.dumps(comp_data)
                sign_for_dignity = comp_id
            elif comp_type == 'house':
                replacements['[HOUSE_DATA]'] = json.dumps(comp_data)
                # **CORRECTED LOGIC**: Extract quality from the full house data object
                quality_data = comp_data.get("quality", "N/A").capitalize()
            elif comp_type == 'node': replacements['[NODE_DATA]'] = json.dumps(comp_data)
            elif comp_type == 'angle': replacements['[ANGLE_DATA]'] = json.dumps(comp_data)
            elif comp_type == 'dynamic': replacements['[ASPECT_DATA]'] = json.dumps(comp_data)
        
        # **CORRECTED LOGIC**: Derive dignity if applicable for the synthesis type
        if synthesis_type == 'planet_in_sign' and planet_for_dignity and sign_for_dignity:
            dignity_status = self._get_dignity_status(planet_for_dignity, sign_for_dignity)

        replacements['[DIGNITY_STATUS]'] = dignity_status
        replacements['[QUALITY_DATA]'] = quality_data

        prompt_text = self._build_prompt_string(template, replacements)

        return {
            "prompt_text": prompt_text,
            "synthesis_rule_metadata": SynthesisRuleMetadata(**rule_metadata),
            "components_used": components_data
        }

    def assemble_manifestation_prompt(self, components_input: List[Dict[str, str]], chosen_valence: Valence, life_area: str) -> str:
        """Assembles the prompt for Stage 2: Generating Manifestations."""
        template = MANIFESTATION_PROMPTS.get(life_area)
        if not template:
            raise ValueError(f"No manifestation prompt template found for life area: {life_area}")

        # Create a simple, human-readable string representation of the astrological signature
        component_names = [c['id'].replace('_', ' ').title() for c in components_input]
        signature_str = " ".join(component_names)
        
        replacements = {
            '[SIGNATURE_DATA]': signature_str,
            '[VALENCE_DATA]': chosen_valence.json()
        }

        return self._build_prompt_string(template, replacements)
